export const ADD_SPONSER = 'ADD_SPONSER';
export const DELETE_SPONSER = 'DELETE_SPONSER';
export const EDIT_SPONSER = 'EDIT_SPONSER';
export const FETCH_SPONSERS = 'FETCH_SPONSERS';
export const FETCH_SPONSERS_SUCCESS = 'FETCH_SPONSERS_SUCCESS';
